module.exports={
	"port":3000,
	"webroot":"./../test",
	"context":"",
	"debug":true,
	"index":"test.html",
	"unicode":"utf-8",
	"controller":"./config/ctrls_config",
	"mine":"./config/mine_config",
	"cache":"./temp"
};